name: 'rootly-pulse'
description: 'Create a new rootly pulse'
branding:
  icon: 'alert-triangle'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  summary:
    description: Summary of the pulse
    required: true
  api_key:
    description: A api key for rootly
    required: true
  environment:
    description: Environments associated with the pulse. CSV value so no spaces before or after ,
    required: false
  service:
    description: Services associated with the pulse. CSV value so no spaces before or after ,
    required: false
  label:
    description: Labels associated with the pule CSV value with key value pairs being separated with a =. No spaces before or after = and ,
    required: false
