name: 'rootly-pulse'
description: 'Create a new rootly pulse'
branding:
  icon: 'alert-triangle'
  color: 'green'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  summary:
    description: Summary of the pulse
    required: true
  api_key:
    description: A API key for rootly
    required: true
  environments:
    description: Environments associated with the pulse. Separate with commas.
    required: false
  services:
    description: Services associated with the pulse. Separate with commas.
    required: false
  labels:
    description: Labels associated with the pulse. Separate with commas and separate key-value pair with = (no spaces before or after =).
    required: false
  source:
    description: Source of the pulse
    required: false
  refs:
    description: Refs associated with the pulse. Separate with commas and separate key-value pair with = (no spaces before or after =).
